version: "3"

services:
  my-app:
    container_name: my-app
    build:
      context: ./php
    ports:
      - 8000:443
    volumes:
      - ./php/apache:/etc/apache2/sites-available/ssl
      - ./php:/app
  
  my-app2:
    container_name: my-app2
    build:
      context: ./php2
    ports:
      - 8001:443
    volumes:
      - ./php2/apache:/etc/apache2/sites-available/ssl
      - ./php2:/app